// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

[Keyless]
public partial class ActorCountRegions
{
    public long RowId { get; set; }

    [StringLength(16)]
    [Unicode(false)]
    public string Region { get; set; } = null!;

    public int? Number { get; set; }

    public int? Total { get; set; }

    [Column(TypeName = "decimal(19, 7)")]
    public decimal? Percentage { get; set; }
}