// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class ActorGallery
{
    [Key]
    public int GalleryId { get; set; }

    public int ActorId { get; set; }

    public byte[]? Image { get; set; }

    [ForeignKey("ActorId")]
    [InverseProperty("ActorGallery")]
    public virtual Actor Actor { get; set; } = null!;
}