// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class Actor
{
    [Key]
    public int ActorId { get; set; }

    [StringLength(255)]
    public string? FullName { get; set; }

    [Column(TypeName = "date")]
    public DateTime? BirthDate { get; set; }

    [StringLength(255)]
    public string? BirthPlace { get; set; }

    public int? Country { get; set; }

    public int? Age { get; set; }

    public int? Gender { get; set; }

    public double? Height { get; set; }

    [StringLength(255)]
    public string? Occupations { get; set; }

    public double? Rating { get; set; }

    public string? BioSummary { get; set; }

    public byte[]? Photo { get; set; }

    [InverseProperty("Actor")]
    public virtual ICollection<ActorFilms> ActorFilms { get; set; } = new List<ActorFilms>();

    [InverseProperty("Actor")]
    public virtual ICollection<ActorGallery> ActorGallery { get; set; } = new List<ActorGallery>();

    [InverseProperty("Actor")]
    public virtual ICollection<FilmActor> FilmActor { get; set; } = new List<FilmActor>();
}