// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

[Keyless]
public partial class ActorInfo
{
    public int ActorId { get; set; }

    [StringLength(255)]
    public string? FullName { get; set; }

    [Column("DOB")]
    [StringLength(30)]
    [Unicode(false)]
    public string? Dob { get; set; }

    [StringLength(255)]
    public string? BirthPlace { get; set; }

    [StringLength(50)]
    public string? Country { get; set; }

    public int? Age { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? Height { get; set; }

    [StringLength(255)]
    public string? Occupations { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string? Rating { get; set; }

    public byte[]? Photo { get; set; }

    public string? BioSummary { get; set; }
}