// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class ActorFilms
{
    [Key]
    public int Id { get; set; }

    public int ActorId { get; set; }

    public int Year { get; set; }

    [StringLength(255)]
    public string? Title { get; set; }

    [StringLength(150)]
    public string? Role { get; set; }

    [StringLength(255)]
    public string? Notes { get; set; }

    [ForeignKey("ActorId")]
    [InverseProperty("ActorFilms")]
    public virtual Actor Actor { get; set; } = null!;
}