// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class Country
{
    [Key]
    public int CountryId { get; set; }

    [StringLength(50)]
    public string? Name { get; set; }

    [StringLength(50)]
    public string? Capital { get; set; }

    public int? Population { get; set; }

    public byte[]? Flag { get; set; }

    public int? Region { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<FilmCountry> FilmCountry { get; set; } = new List<FilmCountry>();

    [ForeignKey("Region")]
    [InverseProperty("Country")]
    public virtual Regions? RegionNavigation { get; set; }
}