// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class Film
{
    [Key]
    public int FilmId { get; set; }

    [StringLength(255)]
    public string? Title { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ReleaseDate { get; set; }

    public int? ReleaseYear { get; set; }

    public int? RunningTime { get; set; }

    public string? PlotSummary { get; set; }

    public long? Budget { get; set; }

    public long? BoxOffice { get; set; }

    public int? Language { get; set; }

    [StringLength(255)]
    public string? Director { get; set; }

    [StringLength(255)]
    public string? Producer { get; set; }

    public string? TrailerLink { get; set; }

    public double? Rating { get; set; }

    public string? Genres { get; set; }

    public byte[]? Poster { get; set; }

    [InverseProperty("Film")]
    public virtual ICollection<FilmActor> FilmActor { get; set; } = new List<FilmActor>();

    [InverseProperty("Film")]
    public virtual ICollection<FilmCompany> FilmCompany { get; set; } = new List<FilmCompany>();

    [InverseProperty("Film")]
    public virtual ICollection<FilmCountry> FilmCountry { get; set; } = new List<FilmCountry>();
}