// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class FilmCompany
{
    [Key]
    public int Id { get; set; }

    public int FilmId { get; set; }

    public int StudioId { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("FilmCompany")]
    public virtual Film Film { get; set; } = null!;

    [ForeignKey("StudioId")]
    [InverseProperty("FilmCompany")]
    public virtual MovieStudio Studio { get; set; } = null!;
}