// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

[Keyless]
public partial class FilmActors
{
    public int Id { get; set; }

    public int FilmId { get; set; }

    [StringLength(255)]
    public string? ActorName { get; set; }

    [StringLength(50)]
    public string? Role { get; set; }

    public string? Notes { get; set; }

    public byte[]? Photo { get; set; }
}