// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

[Keyless]
public partial class FilmInfo
{
    public int FilmId { get; set; }

    [StringLength(255)]
    public string? Title { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ReleaseDate { get; set; }

    public int? ReleaseYear { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string? RunningTime { get; set; }

    [StringLength(4000)]
    public string? Budget { get; set; }

    [StringLength(4000)]
    public string? BoxOffice { get; set; }

    [StringLength(50)]
    public string Language { get; set; } = null!;

    [StringLength(255)]
    public string? Director { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string? Rating { get; set; }

    public string? Genres { get; set; }

    public string? TrailerLink { get; set; }

    public byte[]? Poster { get; set; }

    public string? PlotSummary { get; set; }
}