// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class MusicGenre
{
    [Key]
    public int GenreId { get; set; }

    [StringLength(50)]
    public string? GenreName { get; set; }
}