// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Artemis.Dal.Models;

public partial class Regions
{
    [Key]
    public int RegionId { get; set; }

    [StringLength(50)]
    public string? RegionText { get; set; }

    [InverseProperty("RegionNavigation")]
    public virtual ICollection<Country> Country { get; set; } = new List<Country>();
}